### ISSUE TITLE
Will this be coming to Craft3?

### ISSUE THREAD

**Issue by baileydoestech** [pixelandtonic/RedactorStyles#1]
Now that the core redactor plugin has been updated...

**Comment by brandonkelly** [comment]
No need, as the Redactor plugin ships with all of Imperavi’s plugins now, and even lets you supply your own Redactor plugins w/out writing a Craft plugin.

**Comment by brandonkelly** [comment]
There is a slight complication with the Styles plugin, in that any styles it supplies must be hard-coded into the plugin file. We’ve reached out to Imperavi in hopes that they will make it configurable, but in the meantime you can just copy the plugin into your `config/redactor/plugins/` folder and modify it however you need. (See craftcms/redactor#38)

**Comment by noxify** [comment]
@brandonkelly - I had the same problem. I have updated the `inlinestyle` plugin to define my own inline styles :)

 https://github.com/noxify/extended_inlinestyle

**Comment by baileydoestech** [comment]
Looks like someone kindly built a plugin! https://github.com/carlcs/craft-redactorcustomstyles
